### ISSUE TITLE
Graphics: Shrinking macOS wallet castrates the amounts

### ISSUE THREAD

**Issue by kyeno** [devaultcrypto/devault#106]
When shrinking macOS wallet to it's minimum width, it adds a horizontal scrollbar
 and castrates the "DVT/mDVT" dropdown.
![Screen Shot 2019-04-24 at 1 35 03 PM](https://user-images.githubusercontent.com/1790957/56656559-1a119c00-6696-11e9-81e8-603cad24d447.png)

**Comment by proteanx** [comment]
Took me a bit to reproduce but was able to do so. Will work on this. Strangely if you expand to where the unit box (DVT/mDVT) is fully visible and then close and re-open the client, it will not allow you to shrink the client to where it cuts off again. (this has been the behavior on linux at least)

**Comment by kyeno** [comment]
Intersting, I shall check it out. :)

**Comment by proteanx** [comment]
Should be resolved in https://github.com/devaultcrypto/devault/commit/d5d214d7ad8bc2bd89ce476369087e64b7ee91ac (I hope). Please close after confirming
