### ISSUE TITLE
Killing devaultd (^C) while it's loading genesis block causes exception

### ISSUE THREAD

**Issue by kyeno** [devaultcrypto/devault#125]
I'm not sure if this is even valid or important, but probably better to know.
Try to hit CTRL+C in early stage of devaultd startup with freshly inserted wallet password and no data in `~/.devault/testnet1`
```
2019-05-10T02:48:17Z LoadChainTip: Connecting genesis block...
2019-05-10T02:48:17Z

************************
UNKNOWN EXCEPTION
devault in AppInit()



************************
UNKNOWN EXCEPTION
devault in AppInit()

2019-05-10T02:48:17Z Shutdown: In progress...
2019-05-10T02:48:17Z scheduler thread exit
devaultd: ../../src/txdb.cpp:95: virtual bool CCoinsViewDB::BatchWrite(CCoinsMap&, const uint256&): Assertion `!hashBlock.IsNull()' failed.
Aborted
```

**Comment by jonspock** [comment]
Will put this as a background task. Found one thing I can change but it's practically impossible to be able to isolate this to particular code since it's timing critical as to when the Ctrl-C occurs. Unfortunately it's also likely to result in corrupt files.

**Comment by jonspock** [comment]
OK. We still see the UNKNOWN exception but not the abort. Also, you are able to retry after this without an issue, so closing this
