### ISSUE TITLE
Change Default branch to Master

### ISSUE THREAD

**Issue by 88plug** [devaultcrypto/devault#185]
Please update the github setting for default branch to be set to master.  This will help people that use ```git clone https://github.com/devaultcrypto/devault/``` always be on a working stable release.  You guys are moving fast which is great but keep the default branch as master for what you deliver to the public.

**Comment by jonspock** [comment]
<img width="906" alt="Screen Shot 2019-07-27 at 4 42 17 PM" src="https://user-images.githubusercontent.com/25382027/62000669-9484fa00-b091-11e9-81b3-061f9ca0c6fc.png">

**Comment by jonspock** [comment]
![image0](https://user-images.githubusercontent.com/25382027/62717783-610f6d00-b9b9-11e9-94e0-97179c2a4703.png)

**Comment by jonspock** [comment]
closing this
