### ISSUE TITLE
PPA installs but returns command not found.

### ISSUE THREAD

**Issue by 88plug** [devaultcrypto/devault#186]
To replicate build a Docker container 
FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install software-properties-common -y
RUN add-apt-repository ppa:devault/devault -y
RUN apt-get update
RUN apt-get install devault-qt

Then enter the container and try to run "devault-qt"
Command is not found!  

I had exact same problem on a desktop Ubuntu system and put it in a container just to isolate the issue.  But this is broken outside of Docker too.

**Comment by proteanx** [comment]
xenial is not supported. this package was set for removal but must not have been fully removed. it's removed now.
