### ISSUE TITLE
Document PPA On Website

### ISSUE THREAD

**Issue by 88plug** [devaultcrypto/devault#187]
Update website section to specify which releases are supported.  Sample:
```
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:devault/devault -y
sudo apt-get update
sudo apt-get install devault-qt -y
*** Compatible with Ubuntu 18.04 Bionic Release.
```

**Comment by proteanx** [comment]
We've added "*** Compatible with Ubuntu versions 18.04+ (Bionic, Cosmic & Disco)" to our PPA instructions. Thank you for your recommendation.

**Comment by 88plug** [comment]
The request was for the website so new users who are unfamiliar will directly know if the coin works on their system.  Please consider this for the website.

**Comment by proteanx** [comment]
It's on the website.

**Comment by 88plug** [comment]
![image](https://user-images.githubusercontent.com/19512127/62000704-a1561d80-b092-11e9-927e-9ec0c8934a59.png)
It is not.

**Comment by decentralizd** [comment]
You are cached.

**Comment by 88plug** [comment]
Oh ok - I see it now.
