### ISSUE TITLE
Cannot run binary on Ubuntu

### ISSUE THREAD

**Issue by 88plug** [devaultcrypto/devault#188]
uname -a
Linux 4.15.0-54-generic #58~16.04.1-Ubuntu SMP Mon Jun 24 13:21:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Unpack https://github.com/devaultcrypto/devault/releases/download/v1.0.5/devault-x86_64-1.0.5-linux-gnu.tar.gz and run ./devaultd
```
./devaultd: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./devaultd)
./devaultd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./devaultd)
```

**Comment by proteanx** [comment]
xenial does not support c++17 with their libc version, therefor xenial is not supported. Stable (bionic) and up is supported for linux.
