### ISSUE TITLE
Wallet crashes with segfault when receives CTRL+C on devaultd asking for new password

### ISSUE THREAD

**Issue by kyeno** [devaultcrypto/devault#67]
### Crash
The wallet crashes with "Segmentation fault: 11" in devaultd (console mode) when receives ^C (CTRL+C) while it asks for new wallet password.

Requires an empty blockchain directory.

It was tested with macOS and Linux 32bit and testnet=1 config.

![Screen Shot 2019-04-06 at 1 14 28 AM](https://user-images.githubusercontent.com/1790957/55661272-347cf600-580b-11e9-9f9c-cec39ab73dac.png)

**Comment by jonspock** [comment]
Pushed a change to master. Please try and let me know if issue is fixed

**Comment by kyeno** [comment]
Confirmed to work.
