### ISSUE TITLE
DeVault ignores "addnode=" directives in devault.conf

### ISSUE THREAD

**Issue by kyeno** [devaultcrypto/devault#71]
Tried with both devaultd and devault-qt, tried placing the addnode= both in global (no) section and [testnet] section as it was once advised by the program console itself, but no bonus.
Every time I have to manually perform `addnode X.Y.Z add` in either devault-cli or debug console of devault-qt.

My config for CLI:
```
# Client/wallet
onlynet=ipv4
listen=1
listenonion=0
bind=0.0.0.0
discover=0
dns=0
whitelistrelay=1

# Server/RPC
server=1
rpcuser=xxx
rpcpassword=xxx
rpcbind=127.0.0.1
rpcbind=192.168.1.1
rpcallowip=127.0.0.1
rpcallowip=192.168.0.0/16
rpcthreads=1

# Debugging made easy
printtoconsole=1

# Server made easy
#daemon=1

# DeVault test notwork
testnet=1

[testnet]
addnode=x.y.z
addnode=x.y.z
addnode=x.y.z
# NOTE: tried that both with and without [testnet] section
```

My configure string for CLI:
`--disable-tests --disable-gui-tests --disable-bench --disable-zmq --disable-man --with-gui=no`

**Comment by jonspock** [comment]
The proper setup for adding nodes for testnet is

[test]
addnode=x.y.z

Looks like [testnet] is ignored and it's assumed for mainnet

See example conf here
https://github.com/bitcoin/bitcoin/blob/master/share/examples/bitcoin.conf

**Comment by kyeno** [comment]
Works :)
