### ISSUE TITLE
opening the QT.exe 2nd time you get an error

### ISSUE THREAD

**Issue by decentralizd** [devaultcrypto/devault#73]
https://cdn.discordapp.com/attachments/564986131767361560/564994916758061096/unknown.png

photo of error

Usually have to wipe the roaming folder and re open to fix

**Comment by proteanx** [comment]
This should be resolved via spock's https://github.com/devaultcrypto/devault/commit/91f2256bbe8b324523b77ea88e7c6c79ccd72df4 commit

A new testing candidate release will be available today (will close once multiple windows users confirm fix)

**Comment by kyeno** [comment]
Isn't this related to the bug regarding `debug.log` we encountered today?

**Comment by jonspock** [comment]
No. Not the same thing
