### ISSUE TITLE
Freshly opened devaultd allows empty password while devault-qt does not

### ISSUE THREAD

**Issue by kyeno** [devaultcrypto/devault#78]
Freshly compiled and opened `devaultd` allows just skipping the password dialogue with ENTER key, whilist `devault-qt` does not have such option and forces you to enter a password anyway.

I understand this is for security reasons and probably a good thing in general, but there's an inconsistency. We could either add a "Skip password (I KNOW WHAT I'M DOING!)" button on the qt, or enforce password in `devaultd` somehow.

Also, for UX improvement, we could make the qt's "OK" button clickable if-and-only-if password1 matches password2. It seems a trend in many UIs nowadays.

**Comment by jonspock** [comment]
Thanks Kyeno. This was not intended. I should check for at least a certain number of characters before proceeeding.  
Can you click OK if the passwords are not matching on QT too? Also not intended

**Comment by jonspock** [comment]
Added your last suggestion to the code, will have a PR later

**Comment by jonspock** [comment]
Committed to master, should be in next PPA/release

**Comment by kyeno** [comment]
Confirmed to work
